name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-hack
        version: "^0.5"

    - name: Run cargo hack
      run: cargo hack --version

    - name: Cargo check
      run: cargo check
      
    - name: Format
      run: cargo fmt --check
      
    - name: Linter
      run: cargo clippy
      
    - name: Run tests
      run: cargo test

    - name: Build
      run: cargo build
