name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Install minimal stable with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2

    - name: Cargo check
      run: cargo check
      
    - name: Format
      run: cargo fmt --check
      
    - name: Linter
      run: cargo clippy

    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
        down-flags: "--volumes"
        services: |
          mongodb
      
    - name: Run tests
      run: cargo test

    - name: Build
      run: cargo build
